#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    common: [build, release]
    client-java: [build, release]

build:
  quality:
    filter:
      owner: vaticle
      branch: master
    dependency-analysis:
      image: vaticle-ubuntu-20.04
      command: |
        bazel run @vaticle_dependencies//grabl/analysis:dependency-analysis
  correctness:
#    build:
#      image: vaticle-ubuntu-20.04
#      command: |
#        bazel build //...
#        bazel run @vaticle_dependencies//tool/checkstyle:test-coverage
#        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=streamed
#    build-dependency:
#      image: vaticle-ubuntu-20.04
#      command: |
#        dependencies/maven/update.sh
#        git diff --exit-code dependencies/maven/artifacts.snapshot
#        bazel run @vaticle_dependencies//tool/unuseddeps:unused-deps -- list
    run-typedb:
      machine: 72-core-144-gb
      image: graknlabs-ubuntu-20.04-512-gb # TODO rename to vaticle
      type: background
      timeout: "3h"
      command: |
        export PUBLIC_IP=$(curl -s https://ipinfo.io/ip)
        echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
        cat > typedb.service <<- EOM
        [Unit]
        Description=TypeDB Server

        [Service]
        Type=simple
        Environment=SERVER_JAVAOPTS="-Xmx72G -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1089 -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=$PUBLIC_IP"
        ExecStart=/home/grabl/$GRABL_REPO/dist/typedb-all-linux/typedb server
        Restart=on-failure
        RestartSec=10
        KillMode=process

        [Install]
        WantedBy=multi-user.target
        EOM

        sudo mv typedb.service /etc/systemd/system/
        bazel run //:typedb-extractor-linux -- dist/typedb-all-linux
        cd ./dist/typedb-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start typedb-server
        export GRABL_EXPORT_TYPEDB_SERVER_URI="${HOSTNAME}:1729"
      monitor: |
        sleep 10s
        tail -f -n +1 /home/grabl/$GRABL_REPO/dist/typedb-all-linux/server/logs/typedb.log
    run-biograkn-semmed:
      machine: 32-core-64-gb
      image: graknlabs-ubuntu-20.04-semmed # TODO rename to vaticle
      type: background
      timeout: "3h"
      dependencies: [run-typedb-server]
      command: |
        export PUBLIC_IP=$(curl -s https://ipinfo.io/ip)
        export JVM_OPT="-Xmx30G -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1089 -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=$PUBLIC_IP"
        bazel run --jvmopt="$JVM_OPT" //:migrator -- \
        --source /opt/data \
        --typedb $GRABL_EXPORT_TYPEDB_SERVER_URI \
        --database biograkn-semmed \
        --parallelisation 1024 \
        --batch 32
